project:
  type: website
  output-dir: docs
  title: "Good enough data & systems lab"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: false
    code-fold: true
    code-summary: "Click to expand"
    self-contained: true

website:
  navbar:
    left:
      - text: Home
        href: sig.qmd
      - text: Analysis
        href: sig.qmd
      - text: dontpanic
        href: sig-dontpanic.qmd

execute: 
  error: true
  warning: false
  message: false
  python: .venv/bin/python 
  enabled: true